FROM python:3.12-slim

WORKDIR /app

COPY section-5/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONPATH=/app

EXPOSE 8000

CMD ["uvicorn", "section-5.app:app", "--host", "0.0.0.0", "--port", "8000"]